### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by dane-skipper** [Skipper-Hospitality/organisms#2]
[This package](https://www.jsdelivr.com/package/npm/skipper-organisms) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

Additionally, it doesn't look like the `/dist` minified JS and CSS files are being published to NPM. We should make sure that they are so we can leverage the JSDelivr CDN to allow for inclusions of the assets like:
```
<head>
...
<script src="https://cdn.jsdelivr.net/npm/skipper-organisms@0.0.1/day-range-picker/dist/day-range-picker.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/skipper-organisms@0.0.1/day-range-picker/dist/day-range-picker.css">
</head>
```
We should also include the example of how to use jsDelivr to include these assets in the README

**Comment by nazmuldipu** [comment]
For JS file:
https://cdn.jsdelivr.net/npm/skipper-organisms@0.0.4/dist/day-range-picker.min.js

For CSS file:
https://cdn.jsdelivr.net/npm/skipper-organisms@0.0.4/dist/day-range-picker.min.css

**Comment by nazmuldipu** [comment]
Vite has better support with web application, but it has some limit with library. [Ref](https://github.com/vitejs/vite/issues/330).

I have to change it to webpack.

**Comment by nazmuldipu** [comment]
Our new version 0.0.5 of [Organisms packages](https://www.npmjs.com/package/skipper-organisms) released today with updated structure, config and Added example file and CDN link. Followings are the cds links 

CSS CDN:
`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/skipper-organisms@0.0.5/dist/day-range-picker.min.css">`

Javascript CDN:
`<script src="https://cdn.jsdelivr.net/npm/skipper-organisms@0.0.5/dist/day-range-picker.cjs.min.js"></script>`
`<script src="https://cdn.jsdelivr.net/npm/skipper-organisms@0.0.5/dist/day-range-picker.es.min.js" type="module"></script>`

**Comment by dane-skipper** [comment]
for the last `<script>` tag, wouldn't you want the `type="module"` attribute?

**Comment by dane-skipper** [comment]
nice work!

**Comment by nazmuldipu** [comment]
> for the last `<script>` tag, wouldn't you want the `type="module"` attribute?

Updated,

**Comment by dane-skipper** [comment]
@nazmuldipu if you update the README for organisms with the info contained in [this comment](https://github.com/Skipper-Hospitality/organisms/issues/2#issuecomment-1080543067), then I think we can close out this issue

**Comment by nazmuldipu** [comment]
README updated.
