### ISSUE TITLE
please disable the previous dates in the calendar 

### ISSUE THREAD

**Issue by niazmorshed14** [Skipper-Hospitality/organisms#9]
- [x] please make sure the calendar only shows the current and next dates

**Comment by nazmuldipu** [comment]
@niazmorshed14 developers can set set the minimum and maximum value during integration process.
![image](https://user-images.githubusercontent.com/21059426/163524126-cebae437-4c04-42a0-903b-26bb250b130a.png)

**Comment by niazmorshed14** [comment]
@nazmuldipu bhai, got it. thanks for letting me know. i am going to close this issue.
